# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
target 'WKDouYuZB' do
    
pod 'Alamofire' , '~> 4.4.0'

end
